### PR TITLE
add workflow to auto publish to pypi

### PR DESCRIPTION
**Pull request by congzhangzh**
do automate publish by GitHub action.

**the only work you need to do is configure your PyPI token.**

### reference:

https://packaging.python.org/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/
https://github.com/marketplace/actions/pypi-publish

### CODE REVIEW

**Comment by congzhangzh** [comment]
@dchansen how about this idea?

**Comment by dchansen** [comment]
@congzhangzh  I like it! I had wanted to do this for a while for gadgetron-python and ismrmrd-python. Thanks for implementing!
I'm on vacation for the next week, but I expect we can merge this. 
The only part missing is to make sure that the version inside gadgetron-python has actually been updated (which I often forget).

**Comment by congzhangzh** [comment]
@dchansen the workflow is simple

```bash
git tag -a v0.96.2 -m 'do some release'
git push origin --tags
```

**Comment by congzhangzh** [comment]
I have tested this idea on my own project,  https://github.com/medlab/gadgetron-dataflow-monitor.

you can try to trigger by your self now:)

**Comment by congzhangzh** [comment]
@dchansen how about this pull request, need more adjust?:)

**Pull request merged**
